  ---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upg-loadme
  namespace: demo
spec:
  # Add hpa spec as per requirement
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50